Feat/signup UI
Andy-Golden/find-place-to-live pull request #5
Opened 2023-11-14 02:36 UTC by Andy-Golden

## Task
https://trello.com/c/nUXzcFBN/4-signup-ui-https-previewcolorlibcom-theme-konato-registerhtml

## Description
- Sign up api
- Validate with yup
- 
## Screenshot

https://github.com/Andy-Golden/find-place-to-live/assets/147120986/207abcb1-f6cd-4070-8e9c-fdea0e0c31e5

2023-11-14 17:00 UTC, carl-huynh-goldenowl requested changes

2023-11-14 17:00 UTC, carl-huynh-goldenowl commented on src/constants/strongPassword.ts
> +  /^(?=.*[A-Z])(?=.*[!@#$&*])(?=.*[0-9])(?=.*[a-z].*[a-z].*[a-z]).{6}$/;
- Why is the password length 6?
- Give more defails about your regex (Ex: Length? Uppercase letter?...)

2023-11-14 17:01 UTC, carl-huynh-goldenowl commented
Need to update desc of this PR
<img width="277" alt="Screen Shot 2023-11-15 at 00 00 29" src="https://github.com/Andy-Golden/find-place-to-live/assets/94506012/5ad1be90-bce7-48ea-bb5e-e7068b83991f">

2023-11-14 17:03 UTC, carl-huynh-goldenowl commented
I will review responsive, setup storybook in other PR

2023-11-14 17:15 UTC, carl-huynh-goldenowl commented
Please use other font

2023-11-15 03:33 UTC, Andy-Golden commented
Em sẽ đổi font ở nhánh set up i18n nhe anh

2023-11-15 04:19 UTC, carl-huynh-goldenowl approved these changes
LGTM

2023-11-15 04:28 UTC, merged