Feat: Set up i18n
Andy-Golden/find-place-to-live pull request #6
Opened 2023-11-14 02:44 UTC by Andy-Golden

## Task
https://trello.com/c/fCkdsxlm/44-set-up-i18n-and-apply-storybook

## Description
- Set up i18n
- Apply storybook

## Screenshot

https://github.com/Andy-Golden/find-place-to-live/assets/147120986/fafb6fed-ad95-4e16-8818-cd687799947d

2023-11-14 17:12 UTC, carl-huynh-goldenowl requested changes

2023-11-14 17:12 UTC, carl-huynh-goldenowl commented on public/locales/vi/translation.json
> +    "subTitle": "Tạo tài khoản để sử dụng nhiều tính năng",
This translation does not match with _Create your account to get full access_

2023-11-14 17:12 UTC, carl-huynh-goldenowl commented on src/common/SelectLanguage/helper.ts
> +
Remove this line.

2023-11-14 17:12 UTC, carl-huynh-goldenowl commented on src/common/SelectLanguage/helper.ts
> +
ditto

2023-11-14 17:13 UTC, carl-huynh-goldenowl commented
Missing space
<img width="487" alt="Screen Shot 2023-11-15 at 00 12 42" src="https://github.com/Andy-Golden/find-place-to-live/assets/94506012/d94f7fca-5299-484b-8c0f-1baceae65345">

2023-11-15 03:54 UTC, Andy-Golden commented
I changed font to Jost san-serif
![image](https://github.com/Andy-Golden/find-place-to-live/assets/147120986/b0bf2ba8-2539-4c8f-9404-f86e507ec1b8)

2023-11-15 04:17 UTC, carl-huynh-goldenowl approved these changes
LGTM

2023-11-15 04:27 UTC, merged